apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Corrected 'nodeport' to 'nodePort'
  type: NodePort  # Corrected 'nodeport' to 'NodePort'
